# Intro to PandaPower for IDP Project Optimization

In [1]:
try:
    import matplotlib as plt
    from pandapower.networks.power_system_test_cases import case30
    from pandapower.run import runpp, runopp
    from pandapower.timeseries.run_time_series import run_timeseries, OutputWriter
    from pandapower.diagnostic import Diagnostic
    from pandapower.create import create_storage
    from tools.limits import bus_vm_pu_limits, line_loading_limits
    from tools.jacobian import voltage_sensitivity_matrix, vs_mse   

except: 
    %pip install pandapower
    %pip install numba
    %pip install matplotlib
    %pip install scikit-learn
    import matplotlib as plt
    from pandapower.networks.power_system_test_cases import case30
    from pandapower.run import runpp, runopp
    from pandapower.timeseries.run_time_series import run_timeseries
    from tools.jacobian import voltage_sensitivity_matrix, vs_mse   

from control.battery import Battery
import profileloader as pl
import numpy as np
import os
import tempfile

### Import IEEE Case 30:
Case 30 is stored in a variable, "net", which consists of several dataframes. 
You can conceptualize a dataframe as being like a spreadsheet: It has named rows and columns, and data is stored in individual cells for each row/column pair. 
By default, the IEEE 30 net has a dataframe for each of the following grid components
- bus (30)
- load (21)
- generator (5)
- shunt (2)
- ext_grid (1)
- line (34)
- transformer (7)
- cost (6)

Additional components, such as for storage, motors, etc. can also be added to the net

In [2]:
net = case30()
print(net)

This pandapower network includes the following parameter tables:
   - bus (30 elements)
   - load (20 elements)
   - gen (5 elements)
   - shunt (2 elements)
   - ext_grid (1 element)
   - line (41 elements)
   - poly_cost (6 elements)

In [3]:
net.poly_cost

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2
0,0,ext_grid,0.0,2.00,0.02000,0.0,0.0,0.0
1,0,gen,0.0,1.75,0.01750,0.0,0.0,0.0
2,1,gen,0.0,1.00,0.06250,0.0,0.0,0.0
3,2,gen,0.0,3.25,0.00834,0.0,0.0,0.0
4,3,gen,0.0,3.00,0.02500,0.0,0.0,0.0
5,4,gen,0.0,3.00,0.02500,0.0,0.0,0.0

In [4]:
store_el = create_storage( 
    net, 20, 
    p_mw = 20, 
    q_mvar = 0, 
    controllable=True,
    max_e_mwh = 120, 
    soc_percent=50,
    max_p_mw=60, 
    min_p_mw=-60, 
    max_q_mvar=30,
    min_q_mvar=-30)

print(net)

This pandapower network includes the following parameter tables:
   - bus (30 elements)
   - load (20 elements)
   - storage (1 element)
   - gen (5 elements)
   - shunt (2 elements)
   - ext_grid (1 element)
   - line (41 elements)
   - poly_cost (6 elements)

Specific cells are adjustable based on external data

In [5]:
# for example: set the power consumption of load #1 to 2x its starting value
"""print("Before: " + str(net.load.at[0,'p_mw']))
net.load.at[0,'p_mw'] = 2 * net.load.iloc[0].p_mw
print("After: " + str(net.load.at[0,'p_mw']))

# and: set line loading limit to 50%
print("Before: " + str(net.line.at[10,'max_loading_percent']))
net.line.at[10,'max_loading_percent'] = 0.5
print("After: " + str(net.line.at[10,'max_loading_percent']))"""

# and: set generator 5 to limit to 2x its starting value
print("Before: " + str(net.gen.at[1,'p_mw']))
net.gen.at[4,'p_mw'] = 3 * net.gen.iloc[4].p_mw
print("After: " + str(net.gen.at[4,'p_mw']))

# and: set generator 5 to limit to 2x its starting value
print("Before: " + str(net.gen.at[3,'p_mw']))
net.gen.at[3,'p_mw'] = 3 * net.gen.iloc[3].p_mw
print("After: " + str(net.gen.at[3,'p_mw']))

Before: 21.59
After: 111.0
Before: 19.2
After: 57.599999999999994

### Power flow analysis
Analysis can be run on net using the runpp function. This adds a new set of dataframes to the net, containing result data for each bus, load, generator, etc.

In [6]:
runpp(net)
vs_mse(net)

0.00046612202293460313

You can use the result dataframes to check if power flow data is within the defined limits for each object

In [7]:
# For example, buses:
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
Line #9: Result 108.2913% loading is greater than maximum of 100.0% loading
Line #15: Result 174.128% loading is greater than maximum of 100.0% loading
Line #20: Result 156.6672% loading is greater than maximum of 100.0% loading
Line #21: Result 140.8812% loading is greater than maximum of 100.0% loading
Line #22: Result 122.2404% loading is greater than maximum of 100.0% loading
Line #28: Result 143.748% loading is greater than maximum of 100.0% loading
Line #29: Result 132.5882% loading is greater than maximum of 100.0% loading
Line #30: Result 163.9677% loading is greater than maximum of 100.0% loading
Line #31: Result 217.3782% loading is greater than maximum of 100.0% loading

For purposes of optimization, grid components such as generators and loads have a boolean property called "controllable". If a component's "controllable" property is true, that means that the component can be changed during the optimization algorithm, to find which values produce the optimal grid conditions. Values where "controllable" is false are those which must be kept fixed.  
By default, all sources are controllable, and all loads are not.

In [8]:
try: 
    runopp(net)
except: 
    diag = Diagnostic()
    result = diag.diagnose_network(net, report_style="detailed")

Below, you can see that the controllable grids have had their p_mw values changed. Compare the generator results with the generator results from before:

In [9]:
print(net.gen.head())

   name  bus    p_mw  vm_pu  sn_mva  min_q_mvar  max_q_mvar  scaling  slack  \
0  None    1   60.97    1.0     NaN       -20.0        60.0      1.0  False
1  None   21   21.59    1.0     NaN       -15.0        62.5      1.0  False
2  None   26   26.91    1.0     NaN       -15.0        48.7      1.0  False
3  None   22   57.60    1.0     NaN       -10.0        40.0      1.0  False
4  None   12  111.00    1.0     NaN       -15.0        44.7      1.0  False

   in_service  slack_weight  type  controllable  max_p_mw  min_p_mw  \
0        True           0.0  None          True      80.0       0.0
1        True           0.0  None          True      50.0       0.0
2        True           0.0  None          True      55.0       0.0
3        True           0.0  None          True      30.0       0.0
4        True           0.0  None          True      40.0       0.0

   id_q_capability_characteristic  reactive_capability_curve curve_style
0                            <NA>                      False        None
1                            <NA>                      False        None
2                            <NA>                      False        None
3                            <NA>                      False        None
4                            <NA>                      False        None

In [10]:
# proof that bus max/min values are now accounted for
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
All line loading within limits

To demonstrate optimization working if we set one of the generators to a fixed, non-controllable value:

In [11]:
net.gen.at[4,'p_mw'] = 20
net.gen.at[4, 'controllable'] = False

In [12]:
runpp(net)
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
Line #9: Result 110.8988% loading is greater than maximum of 100.0% loading
Line #28: Result 131.8907% loading is greater than maximum of 100.0% loading
Line #29: Result 195.7788% loading is greater than maximum of 100.0% loading
Line #30: Result 137.9347% loading is greater than maximum of 100.0% loading
Line #31: Result 150.3774% loading is greater than maximum of 100.0% loading

In [13]:
runopp(net)
bus_vm_pu_limits(net)
line_loading_limits(net)

All buses within limits
All line loading within limits

The resulting optimized components have changed based on this new constraint.

### Analysis with Custom Data

Load in custom loads/gens from the provided Excel sheets

In [14]:
net=case30()

net.poly_cost["cp2_eur_per_mw2"] = 0        # clear out default costs
store_el = create_storage( 
    net, 5, 
    p_mw = 0, 
    q_mvar = 0, 
    controllable=True,
    max_e_mwh = 20, 
    soc_percent=60,
    max_p_mw=5, 
    min_p_mw=-5, 
    max_q_mvar=5,
    min_q_mvar=-5)


load_control = pl.json_to_net(net, "load", date="1/2/2026")
gen_control = pl.json_to_net(net, "gen", date="1/2/2026")
tariff_control = pl.json_to_net(net, "poly_cost", date="1/2/2026")
storage_control = Battery(net=net, element_index=0)

In [15]:
ow = OutputWriter(net, 
                  output_path="..\\results", 
                  output_file_type='.csv', csv_separator=",")
ow.log_variable("res_storage", "p_mw")
ow.log_variable("storage", "soc_percent")
run_timeseries(net, continue_on_divergence=True
               , max_iteration=40, verbose=True)

No time steps to calculate are specified. I'll check the datasource of the first controller for avaiable time steps
  2%|▏         | 2/96 [00:00<00:09, 10.38it/s]

timestep p_mw=0.0 soc=60.0 pred=-0.10399689874562024
timestep p_mw=-0.10399689874562024 soc=59.86316197533471 pred=-0.10421423496476556

  4%|▍         | 4/96 [00:01<00:43,  2.14it/s]

timestep p_mw=-0.10421423496476556 soc=59.72603798196002 pred=-0.10130448081568655

  5%|▌         | 5/96 [00:02<00:48,  1.89it/s]

timestep p_mw=-0.10130448081568655 soc=59.59274261246569 pred=-0.09645802162839695

  6%|▋         | 6/96 [00:02<00:50,  1.77it/s]

timestep p_mw=-0.09645802162839695 soc=59.46582416295465 pred=-0.10041916557939311

  7%|▋         | 7/96 [00:03<00:51,  1.73it/s]

timestep p_mw=-0.10041916557939311 soc=59.33369368192913 pred=-0.1049001796819278

  8%|▊         | 8/96 [00:04<00:53,  1.64it/s]

timestep p_mw=-0.1049001796819278 soc=59.195667129716064 pred=-0.09855911648063605

  9%|▉         | 9/96 [00:04<00:53,  1.63it/s]

timestep p_mw=-0.09855911648063605 soc=59.06598408171523 pred=-0.09537130224700936

 10%|█         | 10/96 [00:05<00:54,  1.57it/s]

timestep p_mw=-0.09537130224700936 soc=58.94049552612706 pred=-0.09134260224707251

 11%|█▏        | 11/96 [00:06<00:55,  1.54it/s]

timestep p_mw=-0.09134260224707251 soc=58.82030789159144 pred=-0.09335364856523781

 12%|█▎        | 12/96 [00:06<00:54,  1.55it/s]

timestep p_mw=-0.09335364856523781 soc=58.69747414347928 pred=-0.08557796615327115

 14%|█▎        | 13/96 [00:07<00:51,  1.60it/s]

timestep p_mw=-0.08557796615327115 soc=58.58487155643551 pred=-0.09700043509339902

 15%|█▍        | 14/96 [00:08<00:49,  1.66it/s]

timestep p_mw=-0.09700043509339902 soc=58.45723940499683 pred=-0.09461961060555774

 16%|█▌        | 15/96 [00:08<00:47,  1.70it/s]

timestep p_mw=-0.09461961060555774 soc=58.332739917357934 pred=-0.09499861259642667

 17%|█▋        | 16/96 [00:09<00:46,  1.72it/s]

timestep p_mw=-0.09499861259642667 soc=58.20774174288895 pred=-0.09329668158890476

 18%|█▊        | 17/96 [00:09<00:46,  1.69it/s]

timestep p_mw=-0.09329668158890476 soc=58.0849829513246 pred=-0.08245407209561406

 19%|█▉        | 18/96 [00:10<00:47,  1.65it/s]

timestep p_mw=-0.08245407209561406 soc=57.97649075119879 pred=-0.08529371561301728

 20%|█▉        | 19/96 [00:11<00:48,  1.59it/s]

timestep p_mw=-0.08529371561301728 soc=57.864262178023765 pred=-0.07946878528134645

 21%|██        | 20/96 [00:11<00:49,  1.54it/s]

timestep p_mw=-0.07946878528134645 soc=57.7596979868641 pred=-0.08336993395860609

 22%|██▏       | 21/96 [00:12<00:49,  1.51it/s]

timestep p_mw=-0.08336993395860609 soc=57.650000705339615 pred=-0.08346360273211624

 23%|██▎       | 22/96 [00:13<00:50,  1.47it/s]

timestep p_mw=-0.08346360273211624 soc=57.54018017542894 pred=-0.08871305947160645

 24%|██▍       | 23/96 [00:13<00:46,  1.57it/s]

timestep p_mw=-0.08871305947160645 soc=57.423452465597876 pred=-0.08518485725126194

 25%|██▌       | 24/96 [00:14<00:46,  1.54it/s]

timestep p_mw=-0.08518485725126194 soc=57.31136712710937 pred=-0.11578727565425238

 26%|██▌       | 25/96 [00:14<00:44,  1.59it/s]

timestep p_mw=-0.11578727565425238 soc=57.159015448616934 pred=-0.17269714920993742

 27%|██▋       | 26/96 [00:15<00:43,  1.62it/s]

timestep p_mw=-0.17269714920993742 soc=56.93178235755123 pred=-0.16780527938617568

 28%|██▊       | 27/96 [00:16<00:40,  1.70it/s]

timestep p_mw=-0.16780527938617568 soc=56.71098593730626 pred=-0.18920480229455225

 29%|██▉       | 28/96 [00:16<00:39,  1.74it/s]

timestep p_mw=-0.18920480229455225 soc=56.46203225007659 pred=-0.22576726923194904

 30%|███       | 29/96 [00:17<00:38,  1.76it/s]

timestep p_mw=-0.22576726923194904 soc=56.16497005371876 pred=-0.2670618806636766

 31%|███▏      | 30/96 [00:17<00:39,  1.68it/s]

timestep p_mw=-0.2670618806636766 soc=55.81357284231919 pred=-0.3933582273837855

 32%|███▏      | 31/96 [00:18<00:37,  1.71it/s]

timestep p_mw=-0.3933582273837855 soc=55.295996227340524 pred=-0.46527816939988287

 33%|███▎      | 32/96 [00:18<00:35,  1.79it/s]

timestep p_mw=-0.46527816939988287 soc=54.6837881097091 pred=-0.4636428421952351

 34%|███▍      | 33/96 [00:19<00:34,  1.83it/s]

timestep p_mw=-0.4636428421952351 soc=54.07373173839958 pred=-0.4031630147475566

 35%|███▌      | 34/96 [00:19<00:33,  1.85it/s]

timestep p_mw=-0.4031630147475566 soc=53.54325408741595 pred=-0.42568058992766344

 36%|███▋      | 35/96 [00:20<00:33,  1.84it/s]

timestep p_mw=-0.42568058992766344 soc=52.98314804803745 pred=-0.46777359227707094

 38%|███▊      | 36/96 [00:21<00:32,  1.86it/s]

timestep p_mw=-0.46777359227707094 soc=52.36765647925183 pred=-0.4692758501099601

 39%|███▊      | 37/96 [00:21<00:32,  1.84it/s]

timestep p_mw=-0.4692758501099601 soc=51.750188255422934 pred=-0.38648361712924784

 40%|███▉      | 38/96 [00:22<00:32,  1.79it/s]

timestep p_mw=-0.38648361712924784 soc=51.24165718025287 pred=-0.3415055803239973

 41%|████      | 39/96 [00:22<00:33,  1.69it/s]

timestep p_mw=-0.3415055803239973 soc=50.79230773245814 pred=-0.36144888305618667

 42%|████▏     | 40/96 [00:23<00:33,  1.66it/s]

timestep p_mw=-0.36144888305618667 soc=50.31671709685789 pred=-0.3452164206107899

 43%|████▎     | 41/96 [00:24<00:33,  1.62it/s]

timestep p_mw=-0.3452164206107899 soc=49.86248496447527 pred=-0.3495518494808827

 44%|████▍     | 42/96 [00:24<00:33,  1.59it/s]

timestep p_mw=-0.3495518494808827 soc=49.40254832042148 pred=-0.3706164900079221

 45%|████▍     | 43/96 [00:25<00:33,  1.58it/s]

timestep p_mw=-0.3706164900079221 soc=48.91489504409527 pred=-0.37634729217384255

 46%|████▌     | 44/96 [00:26<00:32,  1.61it/s]

timestep p_mw=-0.37634729217384255 soc=48.419701238603366 pred=-0.3413184779834783

 47%|████▋     | 45/96 [00:26<00:32,  1.56it/s]

timestep p_mw=-0.3413184779834783 soc=47.97059797809879 pred=-0.2500954598755434

 48%|████▊     | 46/96 [00:27<00:37,  1.34it/s]

timestep p_mw=-0.2500954598755434 soc=47.641525004578334 pred=-0.27820312301836336

 49%|████▉     | 47/96 [00:28<00:38,  1.28it/s]

timestep p_mw=-0.27820312301836336 soc=47.2754682637647 pred=-0.25871240399883405

 50%|█████     | 48/96 [00:29<00:42,  1.13it/s]

timestep p_mw=-0.25871240399883405 soc=46.9350572058715 pred=-0.2479114615739235

 51%|█████     | 49/96 [00:30<00:38,  1.23it/s]

timestep p_mw=-0.2479114615739235 soc=46.60885791432687 pred=2.0403294971411077

 52%|█████▏    | 50/96 [00:30<00:33,  1.37it/s]

timestep p_mw=2.0403294971411077 soc=49.031749192181934 pred=2.056267226165373

 53%|█████▎    | 51/96 [00:31<00:31,  1.42it/s]

timestep p_mw=2.056267226165373 soc=51.47356652325331 pred=2.0830868284386335

 54%|█████▍    | 52/96 [00:32<00:29,  1.50it/s]

timestep p_mw=2.0830868284386335 soc=53.94723213202419 pred=2.0894225794965307

 55%|█████▌    | 53/96 [00:32<00:27,  1.59it/s]

timestep p_mw=2.0894225794965307 soc=56.42842144517632 pred=2.128067085208013

 56%|█████▋    | 54/96 [00:33<00:25,  1.65it/s]

timestep p_mw=2.128067085208013 soc=58.95550110886084 pred=2.1319584059868153

 57%|█████▋    | 55/96 [00:33<00:23,  1.73it/s]

timestep p_mw=2.1319584059868153 soc=61.48720171597018 pred=2.1443475101964427

 58%|█████▊    | 56/96 [00:34<00:23,  1.72it/s]

timestep p_mw=2.1443475101964427 soc=64.03361438432846 pred=2.1166826065393747

 59%|█████▉    | 57/96 [00:34<00:23,  1.68it/s]

timestep p_mw=2.1166826065393747 soc=66.54717497959396 pred=2.1131641983848857

 60%|██████    | 58/96 [00:35<00:22,  1.67it/s]

timestep p_mw=2.1131641983848857 soc=69.05655746517601 pred=2.105326855795747

 61%|██████▏   | 59/96 [00:36<00:21,  1.68it/s]

timestep p_mw=2.105326855795747 soc=71.55663310643347 pred=2.1321134663576284

 62%|██████▎   | 60/96 [00:36<00:21,  1.69it/s]

timestep p_mw=2.1321134663576284 soc=74.08851784773314 pred=2.1378470377320125

 64%|██████▎   | 61/96 [00:37<00:19,  1.75it/s]

timestep p_mw=2.1378470377320125 soc=76.62721120503991 pred=0.09759838357336903

 65%|██████▍   | 62/96 [00:37<00:19,  1.75it/s]

timestep p_mw=0.09759838357336903 soc=76.7431092855333 pred=0.10354179861192386

 66%|██████▌   | 63/96 [00:38<00:18,  1.74it/s]

timestep p_mw=0.10354179861192386 soc=76.86606517138495 pred=0.08342792032447616

 67%|██████▋   | 64/96 [00:39<00:19,  1.65it/s]

timestep p_mw=0.08342792032447616 soc=76.96513582677026 pred=0.0647224569080073

 68%|██████▊   | 65/96 [00:39<00:19,  1.56it/s]

timestep p_mw=0.0647224569080073 soc=77.04199374434852 pred=-0.4661446806127111

 69%|██████▉   | 66/96 [00:40<00:18,  1.60it/s]

timestep p_mw=-0.4661446806127111 soc=76.42864548038442 pred=-0.4191016670967891

 70%|██████▉   | 67/96 [00:41<00:18,  1.57it/s]

timestep p_mw=-0.4191016670967891 soc=75.87719591841496 pred=-0.33032413652570036

 71%|███████   | 68/96 [00:41<00:17,  1.56it/s]

timestep p_mw=-0.33032413652570036 soc=75.44255889667062 pred=-0.32053329650289264

 72%|███████▏  | 69/96 [00:42<00:17,  1.55it/s]

timestep p_mw=-0.32053329650289264 soc=75.02080455916682 pred=-0.371852706231914

 73%|███████▎  | 70/96 [00:42<00:16,  1.56it/s]

timestep p_mw=-0.371852706231914 soc=74.53152468254588 pred=-0.3529978755899693

 74%|███████▍  | 71/96 [00:43<00:16,  1.55it/s]

timestep p_mw=-0.3529978755899693 soc=74.0670537936117 pred=-0.3354089671580603

 75%|███████▌  | 72/96 [00:44<00:15,  1.54it/s]

timestep p_mw=-0.3354089671580603 soc=73.62572620524584 pred=-0.3136882972879951

 76%|███████▌  | 73/96 [00:44<00:14,  1.55it/s]

timestep p_mw=-0.3136882972879951 soc=73.21297844565638 pred=-0.23805953043854033

 77%|███████▋  | 74/96 [00:45<00:14,  1.49it/s]

timestep p_mw=-0.23805953043854033 soc=72.89974222139514 pred=-0.2189441977971756

 78%|███████▊  | 75/96 [00:46<00:15,  1.40it/s]

timestep p_mw=-0.2189441977971756 soc=72.61165775060938 pred=-0.20783860855034791

 79%|███████▉  | 76/96 [00:47<00:14,  1.35it/s]

timestep p_mw=-0.20783860855034791 soc=72.33818589725367 pred=-0.21914786602659325

 80%|████████  | 77/96 [00:47<00:13,  1.38it/s]

timestep p_mw=-0.21914786602659325 soc=72.04983344195551 pred=-0.17985401894571804

 81%|████████▏ | 78/96 [00:48<00:12,  1.40it/s]

timestep p_mw=-0.17985401894571804 soc=71.81318341702693 pred=-0.15016852636452385

 82%|████████▏ | 79/96 [00:49<00:11,  1.43it/s]

timestep p_mw=-0.15016852636452385 soc=71.61559325075783 pred=-0.12897148605328662

 83%|████████▎ | 80/96 [00:50<00:11,  1.38it/s]

timestep p_mw=-0.12897148605328662 soc=71.4458939270035 pred=-0.12906744190236008

 84%|████████▍ | 81/96 [00:50<00:10,  1.46it/s]

timestep p_mw=-0.12906744190236008 soc=71.27606834555303 pred=-0.11180059426980551

 85%|████████▌ | 82/96 [00:51<00:09,  1.42it/s]

timestep p_mw=-0.11180059426980551 soc=71.12896230046118 pred=-0.11785471620312393

 86%|████████▋ | 83/96 [00:52<00:08,  1.45it/s]

timestep p_mw=-0.11785471620312393 soc=70.97389030545708 pred=-0.09750229697789714

 88%|████████▊ | 84/96 [00:52<00:08,  1.46it/s]

timestep p_mw=-0.09750229697789714 soc=70.84559780943353 pred=-0.09463227043667657

 89%|████████▊ | 85/96 [00:53<00:07,  1.50it/s]

timestep p_mw=-0.09463227043667657 soc=70.72108166412211 pred=-0.08374886281508742

 90%|████████▉ | 86/96 [00:54<00:06,  1.49it/s]

timestep p_mw=-0.08374886281508742 soc=70.61088579199699 pred=-0.09115013978416939

 91%|█████████ | 87/96 [00:54<00:05,  1.51it/s]

timestep p_mw=-0.09115013978416939 soc=70.49095139754414 pred=-0.08723058062397993

 92%|█████████▏| 88/96 [00:55<00:05,  1.54it/s]

timestep p_mw=-0.08723058062397993 soc=70.37617431777575 pred=-0.0911296727764594

 93%|█████████▎| 89/96 [00:56<00:04,  1.48it/s]

timestep p_mw=-0.0911296727764594 soc=70.2562668535962 pred=-0.09844610020454773

 94%|█████████▍| 90/96 [00:56<00:04,  1.40it/s]

timestep p_mw=-0.09844610020454773 soc=70.1267325112218 pred=-0.08475358003657268

 95%|█████████▍| 91/96 [00:57<00:03,  1.45it/s]

timestep p_mw=-0.08475358003657268 soc=70.01521464275262 pred=-0.07820138165536457

 96%|█████████▌| 92/96 [00:58<00:02,  1.50it/s]

timestep p_mw=-0.07820138165536457 soc=69.91231808794294 pred=-0.0782383428004553

 97%|█████████▋| 93/96 [00:58<00:01,  1.56it/s]

timestep p_mw=-0.0782383428004553 soc=69.8093729000476 pred=-0.08870024015082308

 98%|█████████▊| 94/96 [00:59<00:01,  1.58it/s]

timestep p_mw=-0.08870024015082308 soc=69.69266205774389 pred=-0.09553121902592145

 99%|█████████▉| 95/96 [01:00<00:00,  1.47it/s]

timestep p_mw=-0.09553121902592145 soc=69.56696308534136 pred=-0.09679110643274341

100%|██████████| 96/96 [01:00<00:00,  1.50it/s]

timestep p_mw=-0.09679110643274341 soc=69.4396063663509 pred=-0.10142121568362666

100%|██████████| 96/96 [01:01<00:00,  1.56it/s]

In [16]:
net.poly_cost

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2
0,0,ext_grid,0.0,0.000132,0,0.0,0.0,0.0
1,0,gen,0.0,0.000000,0,0.0,0.0,0.0
2,1,gen,0.0,0.000000,0,0.0,0.0,0.0
3,2,gen,0.0,0.000000,0,0.0,0.0,0.0
4,3,gen,0.0,0.000000,0,0.0,0.0,0.0
5,4,gen,0.0,0.000000,0,0.0,0.0,0.0